<?php /** @var \Snowdog\DevTest\Controller\IndexAction $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cache Warmer</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>

<?php \Snowdog\DevTest\Component\Menu::getInstance()->render() ?>

<div class="container">

    <?php if (isset($_SESSION['flash'])): ?>
        <p class="bg-info"><?= $_SESSION['flash'] ?></p>
        <?php unset($_SESSION['flash']) ?>
    <?php endif ?>

    <div>
        <h1>Cache Warmer</h1>
        <?php if ($this->user): ?>
            <p class="bg-success">Hello <?= $this->user->getDisplayName() ?>!</p>

            <div class="bg-info">
                <?php $userStats = $this->getUserStats(); ?>
                <strong>Your stats are:</strong>
                <br>
                <ul>
                    <li><strong>Total num of pages:</strong> <?= $userStats['pagesCount'] ?></li>
                    <li><strong>Least recently visited page:</strong>
                        <br>
                        <?php if ($userStats['leastRecent'] instanceof \Snowdog\DevTest\Model\Page): ?>
                            <?= $userStats['leastRecent']->getUrl() ?>
                            <br>
                            <?= $userStats['leastRecent']->getLastView(); ?>
                        <?php else: ?>
                            N/A
                        <?php endif; ?>
                    </li>
                    <li><strong>Most recently visited page:</strong>
                        <br>
                        <?php if ($userStats['mostRecent'] instanceof \Snowdog\DevTest\Model\Page): ?>
                            <?= $userStats['mostRecent']->getUrl() ?>
                            <br>
                            <?= $userStats['mostRecent']->getLastView(); ?>
                        <?php else: ?>
                            N/A
                        <?php endif; ?>
                    </li>
                </ul>
            </div>

            <div class="padded">
                <form class="form-inline" method="post" action="/website">
                    <div class="form-group">
                        <label for="exampleInputName2">Name</label>
                        <input type="text" name="name" class="form-control" id="exampleInputName2"
                               placeholder="My Website">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputUrl2">Hostname</label>
                        <input type="text" name="hostname" class="form-control" id="exampleInputUrl2"
                               placeholder="website.org">
                    </div>
                    <button type="submit" class="btn btn-primary">Add Website</button>
                </form>
            </div>


            <div class="padded">
                <table class="table table-striped">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Hostname</th>
                        <th>Num of pages</th>
                        <th>Least recently visited</th>
                        <th>Most recently visited</th>
                    </tr>
                    <?php foreach ($this->getWebsites() as $website): /** @var \Snowdog\DevTest\Model\Website $website */ ?>
                        <?php $websiteStats = $this->getWebsiteStats($website); ?>
                        <tr>
                            <td><?= $website->getWebsiteId() ?></td>
                            <td><a href="/website/<?= $website->getWebsiteId() ?>"><?= $website->getName() ?></a></td>
                            <td><?= $website->getHostname() ?></td>
                            <td><?= $websiteStats['pagesCount']; ?></td>
                            <td>
                                <?php if ($websiteStats['leastRecent'] instanceof \Snowdog\DevTest\Model\Page): ?>
                                    <?= $websiteStats['leastRecent']->getUrl() ?>
                                    <br>
                                    <?= $websiteStats['leastRecent']->getLastView(); ?>
                                <?php else: ?>
                                    N/A
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if ($websiteStats['mostRecent'] instanceof \Snowdog\DevTest\Model\Page): ?>
                                    <?= $websiteStats['mostRecent']->getUrl() ?>
                                    <br>
                                    <?= $websiteStats['mostRecent']->getLastView(); ?>
                                <?php else: ?>
                                    N/A
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </table>
            </div>
        <?php endif ?>
    </div>

</div><!-- /.container -->


</body>
</html>